version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 30s
      start_period: 60s
    networks:
      - task-manager-network

  app:
    build: .
    container_name: task-manager-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - DB_HOST=mysql
      - DB_NAME=taskmanager
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_PORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - task-manager-network

  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    container_name: task-manager-selenium
    depends_on:
      app:
        condition: service_healthy
    environment:
      - APP_URL=http://app:5000
    volumes:
      - ./test-results:/app/test-results
    networks:
      - task-manager-network

volumes:
  mysql_data:

networks:
  task-manager-network:
    driver: bridge 